### ISSUE TITLE
Which middleware runs the reducer when there are two middlewares.

### ISSUE THREAD

**Issue by NimmiW** [learncodeacademy/react-js-tutorials#32]
![image](https://cloud.githubusercontent.com/assets/26009680/23873643/ba2e6a18-0858-11e7-8f7c-d0f4ffae8290.png)

This is my code. I was going through this tutorial 

https://www.youtube.com/watch?v=DJ8fR0mZM44&index=19&list=PLoYCgNOIyGABj2GQSlDRjgvXtqfDxKm5b

Which middleware runs the reducer when there are two middleware? I have logger and Error middleware. Is there a order or something like that?

**Comment by NimmiW** [comment]
I am new to redux and react. therefore pls excuse any fault in my question :)

**Comment by willrstern** [comment]
When you do `applyMiddleware(logger, error)`, that means that the reducer will go through `logger` then `error` in order for each change event.  either of those can modify the new state or terminate the event by not calling next - in which case, the next reducer never fired.

So, in this case, a logger would log every action and call the next middleware
the error middleware will try a next action and error if it doesn't work, it will log the error and not continue on with `next`

So essentially, every middleware fires every time.  That's why you add the `switch`es in there - so each middleware only responds to the actions that it cares about.

**Comment by NimmiW** [comment]
Thank you very much @willrstern I got that :)

**Comment by willrstern** [comment]
Awesome!
